const styles = {
	colors: {
		primary: '#3498db',
		secondary: '#2ecc71',
		background: '#ecf0f1',
		backgroundRed: '#ED123B',
		text: '#A1A1A1',
		border: '#bdc3c7',
		buttonPrimary: '#000000',
		buttonSecondary: '#ffffff',
		tileBackgroundPrimary: '#37FF00',
		tileBackgroundSecondary: '#222222',
		tileBackgroundTertiary: '#0077FF',
		borderRed: '#F03D5F',
	},
	typography: {
		fontFamily: 'Inter Sans, sans-serif',
		fontSize: '16px',
		fontWeight: 'normal',
		textXs: '12px',
		textSm: '14px',
		textMd: '16px',
		textLg: '18px',
		textXl: '20px',
		displayXs: '24px',
		displaySm: '30px',
		displayMd: '36px',
		displayLg: '48px',
		displayXl: '60px',
		displayXxl: '72px',
		lineHeightXs: '18px',
		lineHeightSm: '20px',
		lineHeightMd: '24px',
		lineHeightLg: '28px',
		lineHeightXl: '30px',
		lineHeightDisplayXs: '32px',
		lineHeightDisplaySm: '38px',
		lineHeightDisplayMd: '44px',
		lineHeightDisplayLg: '60px',
		lineHeightDisplayXl: '72px',
		lineHeightDisplayXxl: '90px',
	},
	buttonWidths: {
		small: '80px',
		medium: '120px',
		large: '160px',
	},
	buttonHeights: {
		small: '20px',
		medium: '32px',
		large: '48px',
	},
	space: {
		small: '8px',
		medium: '16px',
		large: '24px',
	},
	inputs: {
		height: '40px',
		padding: '8px',
		borderColor: '#bdc3c7',
	},
	borderRadius: {
		small: '4px',
		medium: '8px',
		large: '12px',
		xLarge: '16px',
		xxLarge: '30px',
	},
	container: {
		small: '640px',
		medium: '768px',
		large: '1024px',
		xLarge: '1280px',
	},
};

export default styles;
