export interface CountryCode {
	code: number;
	iso: string;
	name: string;
	flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
	{ code: 1, iso: 'US', name: 'United States', flag: '🇺🇸' },
	{ code: 1, iso: 'CA', name: 'Canada', flag: '🇨🇦' },
	{ code: 44, iso: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
	{ code: 33, iso: 'FR', name: 'France', flag: '🇫🇷' },
	{ code: 49, iso: 'DE', name: 'Germany', flag: '🇩🇪' },
	{ code: 39, iso: 'IT', name: 'Italy', flag: '🇮🇹' },
	{ code: 34, iso: 'ES', name: 'Spain', flag: '🇪🇸' },
	{ code: 351, iso: 'PT', name: 'Portugal', flag: '🇵🇹' },
	{ code: 31, iso: 'NL', name: 'Netherlands', flag: '🇳🇱' },
	{ code: 32, iso: 'BE', name: 'Belgium', flag: '🇧🇪' },
	{ code: 41, iso: 'CH', name: 'Switzerland', flag: '🇨🇭' },
	{ code: 43, iso: 'AT', name: 'Austria', flag: '🇦🇹' },
	{ code: 46, iso: 'SE', name: 'Sweden', flag: '🇸🇪' },
	{ code: 47, iso: 'NO', name: 'Norway', flag: '🇳🇴' },
	{ code: 45, iso: 'DK', name: 'Denmark', flag: '🇩🇰' },
	{ code: 358, iso: 'FI', name: 'Finland', flag: '🇫🇮' },
	{ code: 48, iso: 'PL', name: 'Poland', flag: '🇵🇱' },
	{ code: 30, iso: 'GR', name: 'Greece', flag: '🇬🇷' },
	{ code: 353, iso: 'IE', name: 'Ireland', flag: '🇮🇪' },
	{ code: 7, iso: 'RU', name: 'Russia', flag: '🇷🇺' },
	{ code: 380, iso: 'UA', name: 'Ukraine', flag: '🇺🇦' },
	{ code: 90, iso: 'TR', name: 'Turkey', flag: '🇹🇷' },
	{ code: 91, iso: 'IN', name: 'India', flag: '🇮🇳' },
	{ code: 86, iso: 'CN', name: 'China', flag: '🇨🇳' },
	{ code: 81, iso: 'JP', name: 'Japan', flag: '🇯🇵' },
	{ code: 82, iso: 'KR', name: 'South Korea', flag: '🇰🇷' },
	{ code: 61, iso: 'AU', name: 'Australia', flag: '🇦🇺' },
	{ code: 64, iso: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
	{ code: 55, iso: 'BR', name: 'Brazil', flag: '🇧🇷' },
	{ code: 52, iso: 'MX', name: 'Mexico', flag: '🇲🇽' },
	{ code: 54, iso: 'AR', name: 'Argentina', flag: '🇦🇷' },
	{ code: 56, iso: 'CL', name: 'Chile', flag: '🇨🇱' },
	{ code: 57, iso: 'CO', name: 'Colombia', flag: '🇨🇴' },
	{ code: 51, iso: 'PE', name: 'Peru', flag: '🇵🇪' },
	{ code: 27, iso: 'ZA', name: 'South Africa', flag: '🇿🇦' },
	{ code: 234, iso: 'NG', name: 'Nigeria', flag: '🇳🇬' },
	{ code: 254, iso: 'KE', name: 'Kenya', flag: '🇰🇪' },
	{ code: 20, iso: 'EG', name: 'Egypt', flag: '🇪🇬' },
	{ code: 212, iso: 'MA', name: 'Morocco', flag: '🇲🇦' },
	{ code: 971, iso: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
	{ code: 966, iso: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
	{ code: 972, iso: 'IL', name: 'Israel', flag: '🇮🇱' },
	{ code: 65, iso: 'SG', name: 'Singapore', flag: '🇸🇬' },
	{ code: 60, iso: 'MY', name: 'Malaysia', flag: '🇲🇾' },
	{ code: 66, iso: 'TH', name: 'Thailand', flag: '🇹🇭' },
	{ code: 63, iso: 'PH', name: 'Philippines', flag: '🇵🇭' },
	{ code: 62, iso: 'ID', name: 'Indonesia', flag: '🇮🇩' },
	{ code: 84, iso: 'VN', name: 'Vietnam', flag: '🇻🇳' },
	{ code: 852, iso: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
	{ code: 886, iso: 'TW', name: 'Taiwan', flag: '🇹🇼' },
];

export const DEFAULT_COUNTRY_CODE = COUNTRY_CODES[0]; // US +1
