export enum Actions {
	Add_New_Appointment = 'add_new_appointment',
	Add_New_Task = 'add_new_task',
	Add_New_Project = 'add_new_project',
	Decide_If_Task_Or_Project = 'decide_if_task_or_project',
	Update_Existing_Task = 'update_existing_task',
	Remove_Existing_Task = 'remove_existing_task',
	Mark_Task_As_Done = 'mark_task_as_done',
	Procrastinate_All_Tasks = 'procrastinate_all_tasks',
	Exit_Prompting = 'exit_prompting',
	WhatIf_AddANewAppointment = 'whatif_addanewappointment',
	WhatIf_AddedNewTask = 'whatif_addednewtask',
	WhatIf_EditUpdateTask = 'whatif_editupdatetask',
	WhatIf_ProcrastinateTask = 'whatif_procrastinatetask',
	WhatIf_RemovedTask = 'whatif_removedtask',
	WhatIf_MarkedTaskAsDone = 'whatif_markedtaskasdone',
	WhatIf_ProcrastinateAll = 'whatif_procrastinateall',
	Conversational_And_Not_Supported = 'conversational_and_not_supported',
	None = 'none',
}

export enum Status {
	Parsed = 'parsed',
	Clarification = 'clarification',
	None = 'none',
	Pending = 'pending',
	Executed = 'executed',
	Failed = 'failed',
	Exited = 'exited',
	Disposed = 'disposed',
}
